---
- name: WebSphere Application Server install & configure playbook example
  hosts: was
  vars:
    ibm_user: was
    ibm_root: /soft/IBM
  pre_tasks:
    - name: Install setfacl and (un)zip
      become: yes
      apt:
        name: ['acl', 'zip']
        state: present
      when: ansible_os_family == "Debian"

    - name: Install setfacl and unzip on RedHat
      become: yes
      yum:
        name: ['acl', 'unzip']
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create the {{ibm_user}} user
      become: true
      become_user: root
      user:
        name: "{{ibm_user}}"

    - name: Create the {{ibm_root}} directory
      become: true
      become_user: root
      file:
        path: "{{ibm_root}}"
        state: directory
        owner: "{{ibm_user}}"
        group: "{{ibm_user}}"
        mode: 0750

  roles:
    - { role: iim, iim_src: "downloads/agent.installer.linux.gtk.x86_64_1.8.9002.20181015_1517.zip", iim_user: "{{ibm_user}}" }
    - { role: was, was_src: "downloads/was.repo.9000.base.zip", jdk_src: "downloads/sdk.repo.8030.java8.linux.zip", was_user: "{{ibm_user}}" }
